#parser: 'babel-eslint'
parserOptions:
  sourceType: 'module'
  ecmaVersion: 8
  ecmaFeatures:
    'impliedStrict': true
    # 'jsx': true
plugins: []
extends:
  - 'eslint:recommended'
  #- 'plugin:jsx-control-statements/recommended'
#env:
#  "jsx-control-statements/jsx-control-statements": true
env:
  'es6': true
  'browser': true
  'webextensions': true
  'commonjs': true
  #'node': true
globals:
  #'$': true
  'SystemJS': true
  'require': true
  'require_package': true
  'require_component': true
  'define_component': true
  'exports': true
  'module': true
  'Polymer': true
  'intervention': true
  'positive_goal_info': true
  'goal_info': true
  'tab_id': true
  'session_id': true
  'is_new_session': true
  'is_preview_mode': true
  'is_suggestion_mode': true
  'is_suggestion_mode_optout': true
  'is_previously_seen': true
  'Buffer': true
  'dlog': true
  'parameters': true
  'set_default_parameters': true
rules:
  'no-console': 0
  'no-unused-vars': 0
  'require-yield': 0
  'no-undef': 1
  #'no-unused-vars': ['warn', {args: 'none', vars: 'local'}]
  'comma-dangle': ['warn', 'only-multiline']
  #'strict': 2
  # "jsx-control-statements/jsx-choose-not-empty": 1
  # "jsx-control-statements/jsx-for-require-each": 1
  # "jsx-control-statements/jsx-for-require-of": 1
  # "jsx-control-statements/jsx-if-require-condition": 1
  # "jsx-control-statements/jsx-otherwise-once-last": 1
  # "jsx-control-statements/jsx-use-if-tag": 1
  # "jsx-control-statements/jsx-when-require-condition": 1
  # "jsx-control-statements/jsx-jcs-no-undef": 1
  # "no-undef": 0 # Replace this with jsx-jcs-no-undef
