// this file was generated by scripts/generate_polymer_dependencies
// do not edit this file directly
// instead, edit the corresponding .html file and re-run the script
const {import_dom_modules} = require('libs_frontend/dom_utils')
require('bower_components/polymer/polymer.deps.js')
require('bower_components/polymer-themes/ice.deps.js')
require('bower_components/paper-toast/paper-toast.deps.js')
require('bower_components/paper-item/paper-item.deps.js')
require('components/lazuli-logo-v2.deps.js')
require('components/goal-progress-message.deps.js')
require('bower_components/paper-button/paper-button.deps.js')
require('bower_components/paper-time-picker/paper-time-picker.deps.js')
require('bower_components/paper-progress/paper-progress.deps.js')
require('components/call-to-action-button.deps.js')
import_dom_modules(require('components/banner-netflix-screen.html'), 'components/banner-netflix-screen.html')
require('components/banner-netflix-screen')
