// this file was generated by scripts/generate_polymer_dependencies
// do not edit this file directly
// instead, edit the corresponding .html file and re-run the script
const {import_dom_modules} = require('libs_frontend/dom_utils')
require('bower_components/polymer/polymer.deps.js')
require('bower_components/polymer-themes/ice.deps.js')
require('bower_components/paper-toast/paper-toast.deps.js')
require('bower_components/paper-button/paper-button.deps.js')
import_dom_modules(require('components/enabledisable-intervention-all-sites.html'), 'components/enabledisable-intervention-all-sites.html')
require('components/enabledisable-intervention-all-sites')
