// this file was generated by scripts/generate_polymer_dependencies
// do not edit this file directly
// instead, edit the corresponding .html file and re-run the script
const {import_dom_modules} = require('libs_frontend/dom_utils')
require('bower_components/polymer/polymer.deps.js')
require('bower_components/paper-button/paper-button.deps.js')
require('bower_components/paper-dialog/paper-dialog.deps.js')
require('bower_components/paper-dialog-scrollable/paper-dialog-scrollable.deps.js')
require('bower_components/paper-input/paper-input.deps.js')
require('bower_components/paper-checkbox/paper-checkbox.deps.js')
require('bower_components/paper-input/paper-textarea.deps.js')
require('bower_components/gold-email-input/gold-email-input.deps.js')
require('bower_components/paper-input/paper-textarea.deps.js')
require('bower_components/html-echo/html-echo.deps.js')
import_dom_modules(require('components/feedback-form.html'), 'components/feedback-form.html')
require('components/feedback-form')
