// this file was generated by scripts/generate_polymer_dependencies
// do not edit this file directly
// instead, edit the corresponding .html file and re-run the script
const {import_dom_modules} = require('libs_frontend/dom_utils')
require('bower_components/polymer/polymer.deps.js')
require('components/feedback-form.deps.js')
import_dom_modules(require('components/feedback-button.html'), 'components/feedback-button.html')
require('components/feedback-button')
