// this file was generated by scripts/generate_polymer_dependencies
// do not edit this file directly
// instead, edit the corresponding .html file and re-run the script
const {import_dom_modules} = require('libs_frontend/dom_utils')
require('bower_components/polymer/polymer.deps.js')
require('bower_components/paper-toggle-button/paper-toggle-button.deps.js')
require('bower_components/paper-button/paper-button.deps.js')
require('bower_components/paper-input/paper-input.deps.js')
import_dom_modules(require('components/goal-selector.html'), 'components/goal-selector.html')
require('components/goal-selector')
