// this file was generated by scripts/generate_polymer_dependencies
// do not edit this file directly
// instead, edit the corresponding .html file and re-run the script
const {import_dom_modules} = require('libs_frontend/dom_utils')
require('bower_components/polymer/polymer.deps.js')
require('bower_components/chart-elements/chart-doughnut.deps.js')
import_dom_modules(require('components/graph-donut-top-sites.html'), 'components/graph-donut-top-sites.html')
require('components/graph-donut-top-sites')
