// this file was generated by scripts/generate_polymer_dependencies
// do not edit this file directly
// instead, edit the corresponding .html file and re-run the script
const {import_dom_modules} = require('libs_frontend/dom_utils')
require('bower_components/polymer/polymer.deps.js')
require('bower_components/paper-checkbox/paper-checkbox.deps.js')
require('bower_components/paper-toggle-button/paper-toggle-button.deps.js')
require('components/intervention-parameter-view.deps.js')
require('components/pill-button-group.deps.js')
require('components/enabledisable-intervention-all-sites.deps.js')
require('bower_components/paper-tooltip/paper-tooltip.deps.js')
import_dom_modules(require('components/intervention-view-single-v2.html'), 'components/intervention-view-single-v2.html')
require('components/intervention-view-single-v2')
