// this file was generated by scripts/generate_polymer_dependencies
// do not edit this file directly
// instead, edit the corresponding .html file and re-run the script
const {import_dom_modules} = require('libs_frontend/dom_utils')
require('bower_components/polymer/polymer.deps.js')
require('bower_components/paper-icon-button/paper-icon-button.deps.js')
require('bower_components/paper-button/paper-button.deps.js')
require('bower_components/paper-dropdown-menu/paper-dropdown-menu.deps.js')
require('bower_components/paper-listbox/paper-listbox.deps.js')
require('bower_components/paper-input/paper-input.deps.js')
require('bower_components/iron-ajax/iron-ajax.deps.js')
require('bower_components/paper-tooltip/paper-tooltip.deps.js')
require('bower_components/marked-element/marked-element.deps.js')
import_dom_modules(require('components/intervention-editor-onboard.html'), 'components/intervention-editor-onboard.html')
require('components/intervention-editor-onboard')
