// this file was generated by scripts/generate_polymer_dependencies
// do not edit this file directly
// instead, edit the corresponding .html file and re-run the script
const {import_dom_modules} = require('libs_frontend/dom_utils')
require('bower_components/polymer/polymer.deps.js')
require('bower_components/paper-tooltip/paper-tooltip.deps.js')
require('bower_components/paper-button/paper-button.deps.js')
require('bower_components/paper-icon-button/paper-icon-button.deps.js')
require('bower_components/iron-icons/iron-icons.deps.js')
require('bower_components/paper-dialog/paper-dialog.deps.js')
require('components/feedback-form.deps.js')
import_dom_modules(require('components/lazuli-options-popup-v2.html'), 'components/lazuli-options-popup-v2.html')
require('components/lazuli-options-popup-v2')
