// this file was generated by scripts/generate_polymer_dependencies
// do not edit this file directly
// instead, edit the corresponding .html file and re-run the script
const {import_dom_modules} = require('libs_frontend/dom_utils')
require('bower_components/polymer/polymer.deps.js')
require('bower_components/paper-dialog/paper-dialog.deps.js')
require('bower_components/paper-dropdown-menu/paper-dropdown-menu.deps.js')
require('bower_components/paper-listbox/paper-listbox.deps.js')
require('bower_components/paper-item/paper-item.deps.js')
require('bower_components/paper-input/paper-input.deps.js')
require('components/feedback-button.deps.js')
import_dom_modules(require('components/market-card-detail-dialog.html'), 'components/market-card-detail-dialog.html')
require('components/market-card-detail-dialog')
