// this file was generated by scripts/generate_polymer_dependencies
// do not edit this file directly
// instead, edit the corresponding .html file and re-run the script
const {import_dom_modules} = require('libs_frontend/dom_utils')
require('bower_components/polymer/polymer.deps.js')
require('bower_components/paper-button/paper-button.deps.js')
require('bower_components/paper-range-slider/paper-range-slider.deps.js')
require('bower_components/paper-radio-group/paper-radio-group.deps.js')
require('bower_components/paper-radio-button/paper-radio-button.deps.js')
import_dom_modules(require('components/multi-armed-bandit-debug.html'), 'components/multi-armed-bandit-debug.html')
require('components/multi-armed-bandit-debug')
