// this file was generated by scripts/generate_polymer_dependencies
// do not edit this file directly
// instead, edit the corresponding .html file and re-run the script
const {import_dom_modules} = require('libs_frontend/dom_utils')
require('bower_components/polymer/polymer.deps.js')
require('bower_components/polymer-themes/ice.deps.js')
require('bower_components/paper-button/paper-button.deps.js')
require('bower_components/paper-input/paper-textarea.deps.js')
require('bower_components/paper-card/paper-card.deps.js')
require('bower_components/paper-tabs/paper-tabs.deps.js')
require('bower_components/iron-pages/iron-pages.deps.js')
require('bower_components/paper-toggle-button/paper-toggle-button.deps.js')
require('bower_components/paper-checkbox/paper-checkbox.deps.js')
require('bower_components/iron-ajax/iron-ajax.deps.js')
require('bower_components/paper-slider/paper-slider.deps.js')
import_dom_modules(require('components/popup-view.html'), 'components/popup-view.html')
require('components/popup-view')
