// this file was generated by scripts/generate_polymer_dependencies
// do not edit this file directly
// instead, edit the corresponding .html file and re-run the script
const {import_dom_modules} = require('libs_frontend/dom_utils')
require('bower_components/chart-elements/chart-doughnut.deps.js')
require('bower_components/chart-elements/chart-bar.deps.js')
require('bower_components/chart-elements/chart-horizontal-bar.deps.js')
require('bower_components/chart-elements/chart-line.deps.js')
require('components/goal-progress-view.deps.js')
import_dom_modules(require('components/site-goal-view-v2.html'), 'components/site-goal-view-v2.html')
require('components/site-goal-view-v2')
